CREATE TABLE sensor_readings (
    id bigint generated by default as identity primary key,
    device_id text not null,
    recorded_at timestamptz not null,
    
    temp_1 double precision not null,
    temp_2 double precision not null,
    rpm double precision not null,
    hall_raw integer not null default 0,
    vibration double precision not null,
    voltage double precision not null,
    current double precision not null,
    power double precision not null,
    fan boolean not null,
    
    created_at timestamptz default now()
);

-- Index for faster queries on recent readings per device
CREATE INDEX idx_sensor_readings_device_time ON sensor_readings (device_id, recorded_at DESC);

